// Script: 'testtwo.js' , generated by Gamedonia
describe("Test two", function() {
    
    var env=null;
    
    var user = null;
	var session = null;

    beforeAll(function() {
          env = gamedonia.createTestEnvironment();
          
          // we create a user
          user = env.createUser({name:'Guy', lastname:'Brush', age:27});

          // and log him in
          session = user.login();
    });
     
     afterAll(function() {
    	 
		session.logout();
		user = null;
		session = null;
    
		env.destroy();
		env=null;
    });
     
    it("data api", function() {
     	
		var scriptResult = session.run("apidata");
		expect(scriptResult.isOk()).toBe(true);
  	});
    
	it("users api", function() {
	     	
		var scriptResult = session.run("apiusers");
		expect(scriptResult.isOk()).toBe(true);
	});
	
	it("common script caller", function() {
	 	
		var scriptResult = session.run("caller");
		expect(scriptResult.isOk()).toBe(true);
	});
	
	it("aggregate test", function() {
	 	
		var scriptResult = session.run("aggregate");
		expect(scriptResult.isOk()).toBe(true);
	});
	
	it("specific fields", function() {
	 	
		var scriptResult = session.run("specificfields");
		expect(scriptResult.isOk()).toBe(true);
	});
});