// Script: 'updatetest.js' , generated by Gamedonia
describe("The update function", function() {
    
	// config
	var col_name = "testsapi";
	
    var env=null;
    
    var user = null;
	var session = null;

    beforeAll(function() {
          env = gamedonia.createTestEnvironment();
          
          // we create a user
          user = env.createUser({name:'Guy', lastname:'Brush', age:27});

          // and log him in
          session = user.login();
    });
     
     afterAll(function() {
    	 
		session.logout();
		user = null;
		session = null;
    
		env.destroy();
		env=null;
    });

    it("call update script", function() {
    	
    	var entCount = session.count(col_name, "{}");
		expect(entCount.isOk()).toBe(true);
		expect(entCount.getResult().count).toBe(0);
		
		// insert data
		

    	var scriptResult = session.run("updateslots", {collec:"slots",name:"mine",points:400 });
 	});
});