// Script: 'addslot.js' , generated by Gamedonia
var slot = gamedonia.data.newEntity();

slot.name = request.params.name;
slot.mydate = new Date();
slot.points = request.params.points;

gamedonia.data.create(request.params.collec, slot, {

    success: function(res_create) {

            response.success(res_create);
    },
    error: function(error) {

            log.error(error.message);
            response.error(error.message);
    }
});