// Script: 'aggregate.js' , generated by Gamedonia
var colName = "slots";

var slots = [
{ cust_id: "abc1", status: "A", amount: 50, ord_date: {"@ISODate":"2012-11-02T17:04:11.102Z"} },
{ cust_id: "xyz1", status: "A", amount: 100, ord_date: {"@ISODate":"2012-11-03T17:04:11.102Z"} },
{ cust_id: "xyz1", status: "D", amount: 25, ord_date: {"@ISODate":"2012-11-04T17:04:11.102Z"}  },
{ cust_id: "xyz1", status: "D", amount: 125, ord_date: {"@ISODate":"2012-11-05T17:04:11.102Z"} },
{ cust_id: "abc1", status: "A", amount: 25, ord_date: {"@ISODate":"2012-11-06T17:04:11.102Z"} }
];

function toEntityData(obj){
    var entity = gamedonia.data.newEntity();
    for(prop in obj){
        entity.put(prop,obj[prop]);
    }
    return entity;
}

slots.forEach(function(slot){
    gamedonia.data.create(colName,toEntityData(slot),{
        success: function(o){
            //log.info("inserted slot: " + o);
        }
    });
});

out.println("aa");

gamedonia.data.aggregate(colName, 
[
     '{ $match: { status: "A" } }',
     '{ $group: { _id: "$cust_id", total: { $sum: "$amount" } } }',
     '{ $sort: { total: -1 } }'
 ]
, {
    success: function(c){
	        //out.println("aggregate: " + c);
	        log.info(c);
	        response.success(c);
        }
});