// Script: 'jentity.js' , generated by Gamedonia
require (["libentity"], function(mylib) {
	
	var my_obj = {name:"John"};
	
	var e = mylib.toEntityData(my_obj);
	
	gamedonia.data.create("testsapi", e, {
		
		success: function(res_create) {
			
				log.info(res_create.name);
				response.success();
			},
		error: function(error) {
			
				log.error(error.message);
	            response.error(error.message);
			}	
	});
});