// Script: 'specificfields.js' , generated by Gamedonia
gamedonia.data.search("testsapi", "{}",["name", "score"], 10, "{score:-1}", {

    success: function(res_search){

        log.info(res_search.size());

        if(res_search.length == 0 ) {

            log.info("empty");

        } else {

            log.info(res_search[0].name);
            log.info(res_search[0].date);
            response.success(res_search);
        }

    },
    error:function(error){

        log.error(error.message);
        response.error(error.message);
    }
});